server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
       defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api  #添加路由前缀
  retryable: true
  routes:
    item-service: /mytest/** # 将商品微服务映射到/mytest/**
    # 请求的时候api/mytest-service/mytest
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 熔断超时时长：5000ms
ribbon:
  ConnectTimeout: 1000 #ribbon 连接超时时长
  ReadTimeout: 3500 #ribbon 读取超时时长
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数
